### ISSUE TITLE
Move Ecobee developer API key to config file

### ISSUE THREAD

**Issue by senorshaun** [vojtamolda/homebridge-ecobee3-sensors#13]
I was looking through this project and found you were using your developer api key for these calls. I was wondering if you maybe move that to the config file and have yours by default but easily allow others to change to their own key if they have one

**Comment by vojtamolda** [comment]
Sounds like a good idea. I didn't realize that other people might want to use their dev account.

Do you want to make a pull-request for it?

**Comment by senorshaun** [comment]
sure. looks like you have this repo locked down?  I am unable to create pull requests, upload files, create new branches?

**Comment by vojtamolda** [comment]
Hmm... It shouldn't be locked. Give me a few days, please. I'll check it when I get back home from vacations.
