### ISSUE TITLE
Add exclude remote sensors option to config file

### ISSUE THREAD

**Issue by tekuonline** [vojtamolda/homebridge-ecobee3-sensors#16]
With the recent Firmware Version 3.7.0.969 from Ecobee, sensors (Temperature and Occupancy) are exposed to homekit automatically. Only Humidity sensor is not enabled from Ecobee, which this plugin does. It would be great if we have a config option called ```humidity_only: true```, which would disable the temperature and occupancy through this plugin and enable humidity.

**Comment by vojtamolda** [comment]
Hello @tekuonline,

Thanks for the idea. I think it's really good. My Ecobee just got the update and hopefully this plugin will soon become obsolete :)

Maybe I overlooked something, but compared to this plugin, I'm not getting get any values from the thermostat itself. None of occupancy/temperature/humidity values from the main unit are reported to HomeKit. You can see these?

I know Ecobee reports the target and actual humidity on the _Details_ screen of the thermostat in the _Home_ app. But this screen is hard to get to and I personally prefer to have the humidity visible as it's own tile. Also, the temperature reported by the thermostat is different from the value it actually measures. I have the thermostat placed in the hallway and it's generally colder there, but the reported value is an average from the remote sensors. So for me it makes sense to know the temperature in the hallway.

All the remote sensors are reporting fine. Only the values from the main unit are missing. Maybe doing something like `exclude_sensors: true` would be better. There's already an option `exclude_thermostat`, so `config.json` would be nicely readable and consistent.

**Comment by vojtamolda** [comment]
I just added a new option `exclude_sensors` in the `config.json` file.

@tekuonline if you have a moment, can you try it out and let me know if it solves the problem of duplicated sensors for you? Just get the latest `0.1.3` release from `npm`.
