### ISSUE TITLE
Keeps asking for app registration

### ISSUE THREAD

**Issue by macjeff** [vojtamolda/homebridge-ecobee3-sensors#18]
I run home bridge.   I get code and enter into ecobee.   It creates app.   All works fine.

I have to reboot system or update so I stop home bridge 

I start it back up and it asks me to register again.  Is there no way to have it remember the registration???

thanks,

Jeff

**Comment by vojtamolda** [comment]
Duplicate of #12. Unfortunately, there's not much I can do about this at the moment.
