### ISSUE TITLE
Expose only Humidity sensors to HomeKit

### ISSUE THREAD

**Issue by apexad** [vojtamolda/homebridge-ecobee3-sensors#23]
So, I would really like my house humidity to show up as a sensor, can you help me with the configuration I would need in config.json for this? Otherwise, I don’t want to add anything else.

**Comment by vojtamolda** [comment]
Hello @apexad,

Currently there's no way to display only the humidity value, but you can get pretty close. Only the thermostat itself with it's temperature, humidity and controls can be made visible. If you don't assign the sensors that you don't want to see to any room you'll only encounter them in the "Default Room" in the _Home_ app and nowhere else.

This is the critical section from the [`config.json`](https://github.com/vojtamolda/homebridge-ecobee3-sensors/blob/master/config.json):

```js
...
"exclude_sensors": true,
"exclude_humidity_sensors": false,
"exclude_occupancy_sensors": true,
"exclude_temperature_sensors": true,
"exclude_thermostat": false,
...
```
