### ISSUE TITLE
Esp8266 and bme280?

### ISSUE THREAD

**Issue by ToddGreenfield** [vojtamolda/homebridge-ecobee3-sensors#24]
Related but not specifically- Has anyone created their own ecobee sensors using an Esp8266 and bme280 that somehow integrates with ecobee? I did a quick (really quick) google and didn’t see anything.

**Comment by vojtamolda** [comment]
Try not so quick google search for _Homebridge_ plugins for ESP8266 and you might be more lucky. Also, I’m not sure how exactly do you want to integrate ESP8266 and BME260 with Ecobee.

**Comment by ToddGreenfield** [comment]
Thanks. I am already using homebridge-mcuoit (esp8266) and homebridge-bme280 (RPIz) and those work well for stand-alone temp/humidity sensors. What I was asking and searching for was if anyone has figured a way to integrate something like that with the Ecobee thermostats - so instead of shelling out $80 for two additional Ecobee sensors I would prefer to create some using <$10 worth of parts (ESP01+BME280). Essentially I would like to leverage the FollowMe and other temperature averaging capabilities that the Ecobee thermostats use in conjunction with their sensors. I figured that could be a good addition to this plugin perhaps...

**Comment by vojtamolda** [comment]
Pull request is welcome ;)
