### ISSUE TITLE
Support for exposing humidity in newer Ecobee thermostats 

### ISSUE THREAD

**Issue by rhdny** [vojtamolda/homebridge-ecobee3-sensors#28]
For some reason ecobee does not expose humidity separately in HomeKit as it does temperature, motion, and occupancy. 

This prevents the Home app UI from displaying the humidity under the temperature. 

This very useful homebridge plugin resolves that for my older thermostats but not my newer ones. 

Is it possible to add support for the newer thermostats if even just for humidity (which I believe is the only item ecobee hasn’t addressed since this plugin was created)? 

![A490F17F-7F78-4164-90A0-BF7095152944](https://user-images.githubusercontent.com/79011546/107852117-da70f280-6ddc-11eb-95fa-bb9e9d59e0d8.jpeg)

**Comment by rhdny** [comment]
I was able to resolve by adding the other device names, nikeSmart and apolloSmart to the thermostat validation condition.

**Comment by vojtamolda** [comment]
Nice, @rhdny I'm glad you helped yourself. I'll be happy to accept a PR with your improvements.

**Comment by rhdny** [comment]
Done! Proposed an update frequency setting as well...
