### ISSUE TITLE
Unexpected token e in JSON causing crash

### ISSUE THREAD

**Issue by tbelcher** [vojtamolda/homebridge-ecobee3-sensors#32]
Running homebridge on Raspberry Pi.  The Ecobee sensor plugin had been working properly up until a few days ago, and now with it in my config, Homeridge crashes with this error:
SyntaxError: Unexpected token e in JSON at position 0
Apr 20 14:00:45 raspberrypi homebridge[25375]:     at JSON.parse (<anonymous>)
Apr 20 14:00:45 raspberrypi homebridge[25375]:     at EcobeePlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-ecobee3-sensors/source/platform.js:87:24)
Apr 20 14:00:45 raspberrypi homebridge[25375]:     at IncomingMessage.emit (events.js:327:22)
Apr 20 14:00:45 raspberrypi homebridge[25375]:     at endReadableNT (_stream_readable.js:1220:12)
Apr 20 14:00:45 raspberrypi homebridge[25375]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
Apr 20 14:00:45 raspberrypi homebridge[25375]: [4/20/2021, 2:00:45 PM] Got SIGTERM, shutting down Homebridge...

Any ideas?

Thanks,

Tim

**Comment by vojtamolda** [comment]
Hello Tim,

It's hard for me to say what's going on just from the stack trace. My best guess is that you have a typo in your `config.json` file. Good luck with figuring it out!

  Vojta
