### ISSUE TITLE
Add support for EcoBee premium thermostat model "aresSmart"

### ISSUE THREAD

**Issue by gitBrave-hub** [vojtamolda/homebridge-ecobee3-sensors#39]
Ecobee has a new thermostat with air quality sensor.  It would be great if homebridge-ecobee3-sensors supported the new [model ](https://www.ecobee.com/en-us/smart-thermostats/smart-thermostat-premium/) .  Thanks

**Comment by vojtamolda** [comment]
That would indeed be nice. However, I'm not sure what would be the benefit since this model supports HomeKit natively and also exposes all of the sensors there.

**Comment by vojtamolda** [comment]
Though, feel free to make a PR, @gitBrave-hub I'll be happy to merge it.

**Comment by gitBrave-hub** [comment]
To be sure, it does not expose all of the sensors, that is why I use this.  It does not natively expose the humidity sensor on the thermostat.  And the temperature on the thermostat is indirectly exposed.  And now, Ecobee does not expose the VOC and CO2 sensor data.  I am unfamiliar with this coding environment, perhaps I will try locally and if I have success, I will make a PR.  Thanks

**Comment by vojtamolda** [comment]
Makes sense. Thanks for the explanation!

**Comment by ablyler** [comment]
I have created a PR to add support for the new thermostat. It does not add support for any of the new sensors. https://github.com/vojtamolda/homebridge-ecobee3-sensors/pull/40

**Comment by vojtamolda** [comment]
The patch is available since version [`0.1.9`](https://www.npmjs.com/package/homebridge-ecobee3-sensors/v/0.1.9) on NPM.
