### ISSUE TITLE
add a config option to reduce logging verbosity

### ISSUE THREAD

**Issue by asolochek** [vojtamolda/homebridge-ecobee3-sensors#42]
Currently my homebridge log gets about a dozen lines from the ecobee every 30 seconds. This makes it tricky to find the actual useful information in the log. It would be nice if I could set the plugin to only log errors.

**Comment by vojtamolda** [comment]
That would certainly be nice! Thanks for the tip. I don't have time to work on this but a PR that implements the change would be welcom.

**Comment by tcatlas** [comment]
There is an issue with this, it seems the setup code log message is classified as level 3, whereas it should probably output regardless of the user's log level setting (as well as the waiting for user every 30 seconds messages).
