### ISSUE TITLE
HomeKit functionality for early Ecobee 3 or SmartSi without official HomeKit support

### ISSUE THREAD

**Issue by vojtamolda** [vojtamolda/homebridge-ecobee3-sensors#7]
## If you have an early _Ecobee3_ or _SmartSi_ and want to have unofficial HomeKit support, upvote :+1: this comment.

If your thermostat has the following logo on the box, then it's already HomeKit enabled and you don't need to read any further. [Here](https://ecobee.zendesk.com/hc/en-us/articles/227878287-How-do-I-know-if-my-ecobee3-is-HomeKit-enabled-) is a way to check if you don't have the box anymore.

![homekit-small](https://cloud.githubusercontent.com/assets/8467740/20970944/38c98a6a-bc55-11e6-915f-cbe6b56f5fd5.png)

Please, keep in mind that you'll have to permanently run a [HomeKit server](https://github.com/nfarina/homebridge) on a computer (i.e. Raspberry Pi) that's connected to your home network to get HomeKit to work.

**Comment by vojtamolda** [comment]
Earlier versions of the _Ecobee3_ thermostat were released without HomeKit support. This plugin has a lot of the authorization infrastructure needed to provide unofficial HomeKit functionality to these earlier versions, but some development is still needed to achieve this.

Given enough demand for this issue I'm willing to invest a weekend and work on it just for fun. Thermostats typically last a while and it doesn't really make sense to buy a new one just because Apple released a new protocol to control your house appliances :roll_eyes:

**Note**: According to [this support article](https://ecobee.zendesk.com/hc/en-us/articles/227878207-Can-the-previous-version-of-ecobee3-be-upgraded-to-be-HomeKit-compatible-) there's no way for _Ecobee_ to officially fix this. As far as I know, this is the only way to get HomeKit working with earlier _Ecobee3_. Apple requires all HomeKit enabled devices to have a special [MFi](https://developer.apple.com/programs/mfi/) chip inside that secures (legal) relationship between them and the device manufacturer.

Who knows what kind of deals with the :imp: a company has to sign to get the official blessing from :apple: to put a HomeKit logo on their box...

**Comment by vojtamolda** [comment]
HomeKit (luckily) exposes a relatively limited subset of _Ecobee3_ functions, so there's no need to implement all of the bells and whistles that the official _Ecobee_ API provides. To get it working one needs to create a new accessory that implements a [`Service.Thermostat`](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L2799), which consists of 5 mandatory characteristics:

1. [`Characteristic.CurrentHeatingCoolingState`](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L473)
    This simply gets the current HVAC mode (`Auto|Heat|Cool|Off`). There is a nice API example as part the official Ecobee API documentation [here](https://www.ecobee.com/home/developer/api/examples/ex3.shtml).

2. [`Characteristic.TargetHeatingCoolingState`](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L1805) 
    This sets the current HVAC mode. Example is also available [here](https://www.ecobee.com/home/developer/api/examples/ex8.shtml).

3. [`Characteristic.CurrentTemperature`](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L558)
    Get the current temperature. An example is available [here](https://www.ecobee.com/home/developer/api/examples/ex2.shtml)

4. [`Characteristic.TargetTemperature`](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L1891)
    Set the target heating/cooling temperature. There's a nice example of this in the API docs [here](https://www.ecobee.com/home/developer/api/examples/ex5.shtml).


5. [`Characteristic.TemperatureDisplayUnits`](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L1933)
    There's a `useCelsisus` field that's part of the `Settings` object. The documentation is [here](https://www.ecobee.com/home/developer/api/documentation/v1/objects/Settings.shtml)

**Comment by AppleTechy** [comment]
:+1

**Comment by AppleTechy** [comment]
I am still very interested into seeing this become reality. Definitely willing to spend time trying to test it and sending you the error code it gives if it doesn't work.

**Comment by djrobx** [comment]
I have the official Ecobee3 with HomeKit support but I would still like to see this developed, as its built in support is extremely unreliable, and Ecobee is of no help whatsoever.

**Comment by vojtamolda** [comment]
I don't have any problems with my _Ecobee3_ or _HomeKit_, but thanks for posting a comment here, @djrobx.

**Comment by stromparsons** [comment]
I'd love to see this developed. Been watching for a plugin for homebridge for older ecobees for a while. Would really complete my HomeKit set up to get the ecobee working with everything else. I jumped on the home automation bandwagon early and have managed to get all my other non HomeKit stuff working through homebridge with the exception of the ecobee. Hope more people find this page an up vote.

**Comment by vojtamolda** [comment]
Hello @stromparsons,
Thanks for your comment. If you know of anyone else, please, convince them to upvote this issue. At the moment, I'm not sure if there's big enough demand.

**Comment by sumpy** [comment]
The last post was from a number of months ago, but I would like to add my upvote to get Homebridge support for the early ecobee3 .. and Im sure there are plenty of others out there if they only knew there was such an option.. Hopefully there's a chance this could happen

**Comment by jeffreyjue1** [comment]
I wouldn't mind see this happen with my older Ecobee3.

**Comment by pingje** [comment]
I love seeing my ecobee sensors, I'd be happy to help test support for the older ecobee3.

**Comment by cameronpcook** [comment]
+1 and if there was a way to throw some $ your way Id be happy to

**Comment by stromparsons** [comment]
I found a workaround for this in case anyone is interested.  By running home assistant on a pi with the home bridge plug in, one can gain control of an older ecobee through HomeKit.

**Comment by vojtamolda** [comment]
Thanks @stromparsons! Since there's a workaround I'm closing the issue now.

**Comment by dmitrysergeev** [comment]
@stromparsons can you provide a link to the plugin for SmartSi thermostat?

**Comment by evanhfox** [comment]
@stromparsons What workaround was this? I don't see an ecobee SmartSI compatible plugin from the homebridge library that will allow a SmartSI (in my case) thermostat to be added to Homekit.

**Comment by cgtova** [comment]
I'm very sad.. after finding this issue and thinking there was a solution, I'm sad to discover that in the end there wasn't enough interest. Who has tried this alternative solution from @stromparsons? I haven't found how to implement it. @Vojtamolda, wouldn't you dare to finish this solution? Set yourself up to accept donations :)

**Comment by cgtova** [comment]
Just to add a detail to my request creating the feature of the thermostat control, the method that @stromparsons sent does not work nowadays, as Ecobee does not accept new developers :(

**Comment by stromparsons** [comment]
Hi. I’ve moved homes since last post and have a newer ecobee so don’t use the workaround anymore but what I was doing is running Home Assistant on a raspberry pi which allowed for HomeKit to talk to the ecobee. No idea if it still would work, but here is the link to the home assistant site where you can get the OS to load onto a pi. https://www.home-assistant.io/installation/raspberrypi/


Good luck. 

Edit. Ah I see what you mean about it no longer being possible to get an ecobee developer key. That sucks. TBH this work around was always a bit janky. Recall having to reboot and re-add the home assistant fairly regularly to keep it working. Hope you find another option.
